spring:
  application:
    name: ms-geteway-service
  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
        - id: r1
          uri: http://localhost:8087/
          predicates:
            - Path=/auth/**
        - id: r2
          uri: http://localhost:8000/
          predicates:
            - Path=/events/**
        - id: r3
          uri: http://localhost:8090/
          predicates:
            - Path=/publications/**
        - id: r4
          uri: http://localhost:8100/
          predicates:
            - Path=/profils/**
server:
  port: 8888
